services:
  backend:
    build: ./backend
    container_name: farmer-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    container_name: farmer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
