services:
  backend:
    build: ./backend
    container_name: farmer-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: farmer-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
